### ISSUE TITLE
custom properties and filtering

### ISSUE THREAD

**Issue by fmaritato** [Bynder/bynder-java-sdk#1]
Hi! I'm trying to use the java sdk to query our binder assets. I'm using the below code from your sample:

    BynderService bynderService = BynderServiceImpl.create(new Settings(new URL(url),
                                                                                consumerKey,
                                                                                consumerSecret,
                                                                                token,
                                                                                tokenSecret));
            // Get an instance of the asset bank service to perform Bynder Asset Bank operations.
            AssetBankService assetBankService = bynderService.getAssetBankService();

            // Get media (request with query)
            Response<List<Media>> mediaResponse =
                    assetBankService.getMediaList(new MediaQuery().setType(MediaType.IMAGE)
                                                                  .setLimit(100))
                                    .blockingSingle();

When I set logging to debug, I can see that the returned json contains fields that I would like to retrieve, like 'property_mycustomprop', etc. I don't see how I can pull these items from the returned mediaResponse object as shown above. I see how to get the standard fields like name, height, thumbnails, etc.

If I cannot pull out custom fields from the parsed object, is it possible to get the raw returned json and parse it myself using jackson?

Thanks!

**Comment by danielsequeira** [comment]
Hi Frank,

You are right, at the moment the SDK doesn't parse all the fields in the JSON response of the media call and unfortunately we don't plan on adding them anytime soon, mostly due to our current workload. You can however do the change yourself, but since this is a dynamic field, depending on the metaproperty name, for example it can be: "property_Country", "property_Season", etc. You would need to write a MediaTypeAdapter class that implements the deserialize method from JsonDeserializer<T>, where you will go trough all the JSON objects returned by our API and build the Media object instances yourself. Something like this:

`public class MediaTypeAdapter implements JsonDeserializer<Media> {

    public Media deserialize(final JsonElement json, final Type typeOfT, final JsonDeserializationContext context) {
        GsonBuilder gsonBuilder = new GsonBuilder();
        Gson gson = gsonBuilder.registerTypeAdapter(Boolean.class, new BooleanTypeAdapter()).create();
        Media media = gson.fromJson(json, Media.class);
        JsonObject jsonObject = json.getAsJsonObject();

        for (Map.Entry<String, JsonElement> entry : jsonObject.entrySet()) {
            if (entry.getKey().startsWith("property_")) {
                Map<String, List<String>> metaproperties = new HashMap<>();
                JsonArray jsonArray = entry.getValue().getAsJsonArray();
                List<String> values = new ArrayList<>();
                for (int i = 0; i < jsonArray.size(); i++) {
                    values.add(jsonArray.get(i).getAsString());
                }
                metaproperties.put(entry.getKey(), values);
                media.setMetaproperties(metaproperties);
            }
        }
        return media;
    }
}`

You need then to add this adapter in the createApiService method of the Utils class, so retrofit instantiates our API interface with it.

Finally add the a new member to the Media class to hold this field and a set method for it as well, for example:

`
    private Map<String, List<String>> metaproperties;

    public void setMetaproperties(final Map<String, List<String>> metaproperties) {
        this.metaproperties = metaproperties;
    }`

Cheers,
Daniel

**Comment by fmaritato** [comment]
Thanks Daniel! This is very helpful. I had to modify the adapter slightly because it was only giving me one of the 'property_' items.

        Map<String, List<String>> metaproperties = new HashMap<>();
        for (Map.Entry<String, JsonElement> entry : jsonObject.entrySet()) {
            if (entry.getKey().startsWith("property_")) {
                JsonArray jsonArray = entry.getValue().getAsJsonArray();
                List<String> values = new ArrayList<>();
                for (int i = 0; i < jsonArray.size(); i++) {
                    values.add(jsonArray.get(i).getAsString());
                }
                metaproperties.put(entry.getKey(), values);
            }
        }
        media.setMetaproperties(metaproperties);

Thanks again
