### ISSUE TITLE
Unable To Retrieve Text Type Metaproperty Values

### ISSUE THREAD

**Issue by jeffreychyan-slalom** [Bynder/bynder-java-sdk#10]
Is it possible to retrieve Text type metaproperty values? I have media assets that have data in Text type metaproperties, but I currently don't see a way to retrieve this data because they are not metaproperty options.

I tried turning on `Apifield` for the metaproperty hoping that would somehow expose the text data in the API response for retrieving media assets, but that didn't seem to do anything.

**Comment by danielsequeira** [comment]
Hi Jeffrey,
No, at this moment it is not possible to retrieve those values through the Java SDK.

Metaproperties of type **text** don't follow a structure like other types of metaproperties do like **select**, for metaproperties of type **text** the options are saved as metafields and won't appear under the options field of the metaproperties when you call the _.../api/v4/metaproperties_ endpoint.

The only way to retrieve the options (values) of metaproperties of type **text** is through the _.../api/v4/media_ endpoint. For example if you have a metaproperty of type **text** called "Code" and on a specific asset you create and assign the option "123" for that metaproperty, you will see that data in the asset JSON response as: "property_Code": "123".

The problem is that at this moment we are not deserialising those values from the JSOn response in the Java SDK.

**Comment by danielsequeira** [comment]
@jeffreychyan-slalom is there anything else you need regarding this issue?
