### ISSUE TITLE
NullPointer error while trying to upload

### ISSUE THREAD

**Issue by jms-rupesh-maharjan** [Bynder/bynder-java-sdk#11]
I have been conversing with Ben Smith on this issue, and on his request I'm creating this issue for further analysis.

We're trying to build a mass import tool using the sdk. On a high level, we would like to validate user provided metadata file and upload all the files. At the moment, I am trying to upload one file and validate the upload functionality. This is when I ran into the null pointer error. I am attaching the piece of code that gets triggered when the user hits the upload button on the GUI, and the method that I'm using to instantiate the bynderService. I am also attaching the stacktrace.

Please let me know if I can provide any other information. I can provide the full project if that would be helpful. Any help and guidance would be greatly appreciated. This is business critical and we have a very short time to complete development.

[UploadAction.txt](https://github.com/Bynder/bynder-java-sdk/files/2851270/UploadAction.txt)
[connectToBynder.txt](https://github.com/Bynder/bynder-java-sdk/files/2851264/connectToBynder.txt)
[nullPointer021119.txt](https://github.com/Bynder/bynder-java-sdk/files/2851256/nullPointer021119.txt)

**Comment by jms-rupesh-maharjan** [comment]
Update - I ran the application in a VM, and I get a "Converter did not finished. Upload not completed." error. I believe this is past the point where I was receiving null pointer when I was running it on my machine. Not sure if that is any helpful information to troubleshoot.

I am attaching the stacktrace for the new error
[ConverterNotFinished021119.txt](https://github.com/Bynder/bynder-java-sdk/files/2853010/ConverterNotFinished021119.txt)

**Comment by danielsequeira** [comment]
Hi @jms-rupesh-maharjan and sorry for the late reply.

Yes, it does, this means that the file took too long to be converted and the upload was cancelled. It shouldn't give you a Nullpointer exception though, but throw an exception with that message: "Converter did not finished. Upload not completed.", I will need to check why the Nullpointer is happening.
Are you using the SDK as a reference or do you have it forked?

There's a easy way to fix this which is to increase the number of poll iterations in the `FileUploader` class: https://github.com/Bynder/bynder-java-sdk/blob/master/src/main/java/com/bynder/sdk/service/upload/FileUploader.java#L44 or/and increase the idle time before polling: https://github.com/Bynder/bynder-java-sdk/blob/master/src/main/java/com/bynder/sdk/service/upload/FileUploader.java#L48.

Sometimes depending on the size of the files or "health" status of our servers, conversions during upload can take more time than expected to be finished. In the SDK logic we make the poll status call in 
 loop: https://github.com/Bynder/bynder-java-sdk/blob/master/src/main/java/com/bynder/sdk/service/upload/FileUploader.java#L357 to check when the file(s) finished converting, so we can save the file(s) to Bynder and finalise the upload. Right now the behaviour implemented in order to not let the SDK hanging for too long is to only do a maximum number of poll status calls and when that maximum is reached the SDK throws an exception. Forcing the user to retry the upload.

**Comment by jms-rupesh-maharjan** [comment]
Thank you for the update.

I have the sdk locally. The null pointer only happens when running the application in my machine but doesn't happen in the VM

**Comment by danielsequeira** [comment]
But even if you don't get the NullPointer in your machine, you still get the BynderUploadException with the message "Converter did not finished. Upload not completed."? Or everything works fine on your machine?

**Comment by jms-rupesh-maharjan** [comment]
@danielsequeira, on my machine I do not get the converter not finished. It errors with a null pointer before it even gets there.

I believe it fails because finaliseResponse.body() is null.
From FIleUploader::

if (uploadProgress.areChunksFinished()) {
								// Finalising
								Observable<Response<FinaliseResponse>> finaliseUploadObs = finaliseUpload(
										new FinaliseUploadQuery(uploadRequest.getS3File().getUploadId(),
												uploadRequest.getS3File().getTargetId(), uploadRequest.getS3Filename(),
												uploadProgress.getUploadedChunks()));

								finaliseUploadObs.subscribe(finaliseResponse -> {
									observableEmitter.onNext(uploadProgress);
									
									**String importId = finaliseResponse.body().getImportId();**

**Comment by danielsequeira** [comment]
How big is the file you are trying to upload? I want to see if I can replicate it, because so far I wasn't able to. Every upload works fine for me through the SDK.

**Comment by jms-rupesh-maharjan** [comment]
It happens for every file. 
Let me try using the Java cacerts instead of windows-root, and import our corporate proxy ca into the java cacerts. I have a feeling that might be the issue

**Comment by danielsequeira** [comment]
I checked with a colleague of mine and he confirmed that we didn't change anything regarding this, at least in the last couple of days.

We did replace our SSL certificate, but that was more than a month ago.

For your case he said that it looks like you need to add the SSL certificate to your trust store in Java.
