### ISSUE TITLE
How to output getTags() method

### ISSUE THREAD

**Issue by skhullar-tor** [Bynder/bynder-java-sdk#15]
Hi,

I am new to Java FX and would like to know how to see the tags on the asset.

I called the following - 

// Get all tags (request without query)
	io.reactivex.Observable<Response<List<Tag>>> tagsObservable = assetBankService.getTags();

Now how do we print the list of tags returned.. Any help would be appreciated.

**Comment by danielsequeira** [comment]
Hi @skhullar-tor, sorry for the late reply, are you still having this issue?

Anyway you can always try to get all the tags by executing the `getTags()` method synchronously like this: 
`Response<List<Tag>> tagsResponse = assetBankService.getTags().blockingSingle();`

Then in order to get the `List` of tags you can do:
`List<Tag> tagsList =  tagsResponse.body();`
