### ISSUE TITLE
File is not storing without extension while upload in new Assets and New Versions

### ISSUE THREAD

**Issue by nitin1edate** [Bynder/bynder-java-sdk#94]
We are trying to upload the files. We have the requirement of uploading the  files without extension in the system. But we are not able to upload the same. The code snippet from the SDK,
<img width="665" alt="image" src="https://user-images.githubusercontent.com/118887982/203507620-e7829017-53e3-432c-afc5-a81e1f889589.png">

**Comment by TimBloembergen** [comment]
Hi @nitin1edate, you can resolve this by changing the .setName(uploadQuery).getFilename()). Right now what it does is, it fetches the name that is being used on the upload query. In that upload query the filename needs to be have the extension in order to be uploaded correctly. We just put in that piece of code as a sample so that the uploaded asset has a name. If theres no value being set on the Save call, the asset won't have a name.

You are free to change parameter to whatever the filename needs to be without an extension.

Below are two assets that I uploaded via the API. Both names were set on the last endpoint https://bynder.docs.apiary.io/#reference/upload-assets/6-saving-a-completed-upload/save-as-a-new-asset

![Screenshot 2022-11-23 at 10 17 27](https://user-images.githubusercontent.com/11890097/203509788-a4d0bdbf-f3c0-48da-90a0-ca583ce9df43.png)

![Screenshot 2022-11-23 at 10 16 41](https://user-images.githubusercontent.com/11890097/203509720-3f9911a2-3f66-40b0-9246-2c88dd3c8167.png)

The asset on the right was uploaded without setting a name, the asset on the left was uploaded with a name.

You can achieve the same by changing the parameter .setName to whatever you need the filename to be.

Hope this helps!

**Comment by TimBloembergen** [comment]
Hi Nitin,

No need to cc me on my email, I get notified of your replies via Github :).

What I meant is that you are able to set the name of the asset in the UploadQuery. When we're looking at this sample that we made: https://github.com/Bynder/bynder-java-sdk/blob/a473471e834c19c9639ef1e3ac99110ddbaa5022/src/main/java/com/bynder/sdk/sample/AppSample.java#L66-L70

You are able to pass a name for the asset since we have made that available as well, see here https://github.com/Bynder/bynder-java-sdk/blob/a473471e834c19c9639ef1e3ac99110ddbaa5022/src/main/java/com/bynder/sdk/query/upload/SaveMediaQuery.java#L73-L76

So what you could do to set the name, is this:

String filePath = "your-absolute-filepath";
String brandId = "your-brand-id";
String name = "Nameoftheasset";
UploadQuery uploadQuery = new UploadQuery(filePath, brandId, name);
SaveMediaResponse saveMediaResponse = assetService.uploadFile(uploadQuery).blockingSingle();

When you would run an upload, the file that ends up in the DAM will have the name that you set there.

Can you let me know if that works?

**Comment by nitin1edate** [comment]
hello,

In the given class UploadQuery, we have only one constructor as below which dont have name as 3rd parameter.

<img width="471" alt="image" src="https://user-images.githubusercontent.com/118887982/203536099-ee65a4e7-fa74-4500-ab8a-11d599524c48.png">
So we cannot create the object of UploadQuery as shown above.

regards,

Nitin Edate

**Comment by TimBloembergen** [comment]
Hi @nitin1edate 

We just released a new version of the SDK which allows you to set the name of the file. When you set it, that will be the name that the asset will have in the asset bank (without the extension).

Tim
